apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "infrared.componentName" (dict "root" . "component" "mcp") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "infrared.componentLabels" (dict "root" . "component" "mcp") | nindent 4 }}
  {{- with .Values.mcp.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
