#!/usr/bin/env bash
# Writes charts/infrared/files/image-defaults.yaml from values.yaml: each image's
# default tag and digest. INFRARED_IMAGES hands the operator only the pins that
# differ from these (infrared.imagePins), so a standard install's infrared
# Application carries no pin and a chart upgrade moves its images (drift row 53).
# A template cannot read values.yaml's defaults (.Files leaves it out), hence
# the copy; scripts/verify.sh fails when the two disagree. Run it after any
# change to a default pin: hack/sync-image-defaults.sh [--check]
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
values="$root/charts/infrared/values.yaml"
out="$root/charts/infrared/files/image-defaults.yaml"
gen() {
  echo "# GENERATED by hack/sync-image-defaults.sh from values.yaml: do not edit."
  for c in operator api ui mcp runner; do
    printf '%s:\n  tag: %s\n  digest: %s\n' "$c" "$(yq ".$c.image.tag // \"\"" "$values")" "$(yq ".$c.image.digest // \"\"" "$values")"
  done
  printf 'code-index:\n  tag: %s\n  digest: %s\n' "$(yq '.codeIndex.image.tag // ""' "$values")" "$(yq '.codeIndex.image.digest // ""' "$values")"
}
if [ "${1:-}" = --check ]; then
  diff <(gen) "$out" >/dev/null || { echo "$out is out of date: run hack/sync-image-defaults.sh" >&2; exit 1; }
else
  gen >"$out"
fi
