{{- $c := .Values.operator }}
{{- $ctx := dict "root" . "c" $c "component" "operator" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "infrared.componentName" $ctx }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "infrared.componentLabels" $ctx | nindent 4 }}
spec:
  replicas: {{ $c.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "infrared.selectorLabels" $ctx | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "infrared.componentLabels" $ctx | nindent 8 }}
      {{- with $c.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "infrared.podCommon" $ctx | nindent 6 }}
      terminationGracePeriodSeconds: 10
      containers:
        - name: operator
          {{- include "infrared.containerCommon" $ctx | nindent 10 }}
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
            {{- with $c.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: INFRARED_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: INFRARED_CLUSTER_NAME
              value: {{ .Values.managementCluster.name | quote }}
            - name: INFRARED_VERSION
              value: {{ .Chart.AppVersion | quote }}
            - name: INFRARED_CHART_VERSION
              value: {{ .Chart.Version | quote }}
            - name: INFRARED_IMAGE_PULL_SECRET
              value: {{ include "infrared.firstPullSecret" . | quote }}
            - name: INFRARED_BUILD_REGISTRY
              value: {{ .Values.builds.registry | quote }}
            {{- with $c.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: health
              containerPort: 8081
              protocol: TCP
          {{- include "infrared.probes" (dict "port" "health") | nindent 10 }}
