apiVersion: v1
kind: Service
metadata:
  name: {{ include "infrared.componentName" (dict "root" . "component" "operator") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "infrared.componentLabels" (dict "root" . "component" "operator") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "infrared.selectorLabels" (dict "root" . "component" "operator") | nindent 4 }}
  ports:
    - name: health
      port: {{ .Values.operator.service.port }}
      targetPort: health
      protocol: TCP
