apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "infrared.componentName" (dict "root" . "component" "api") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "infrared.componentLabels" (dict "root" . "component" "api") | nindent 4 }}
  {{- with .Values.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
